kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeserve
      version: v2
  template:
    metadata:
      name: deploy-green
      labels:
        app: kubeserve
        version: v2
    spec:
      containers:
       - name: app
         image: leaddevops/kubeserve:v2
        
---
kind: Service
apiVersion: v1
metadata:
   name: service-v2
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector: 
    app: kubeserve
    version: v2
